version: '3'

services:
  comic-book-reader:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    image: comic-book-reader
    container_name: comic-book-reader
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
      FLASK_ENV: development
    volumes:
      - .:/comic-book-reader